# Generated by Django 5.1.2 on 2024-10-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='opening_balance',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_balance',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
