# Generated by Django 5.1.2 on 2024-11-23 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_request', models.DateTimeField(auto_now_add=True)),
                ('quantity_requested', models.PositiveIntegerField(default=0)),
                ('quantity_restocked', models.PositiveIntegerField(default=0)),
                ('stock_balance', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('issued_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diesel_approvals', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(limit_choices_to={'name': 'Diesel'}, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('restocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diesel_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
