# Generated by Django 5.1.2 on 2024-11-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dieseltracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieseltracker',
            name='product',
        ),
    ]
