# Generated by Django 5.1.2 on 2024-11-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_purchase_coordinator_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='gm_approved',
            field=models.BooleanField(default=True),
        ),
    ]
