# Generated by Django 5.1.2 on 2024-11-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_purchase_gm_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='gm_approved',
            field=models.BooleanField(default=False),
        ),
    ]
