# Generated by Django 5.1.2 on 2024-12-12 08:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/default_image.jpg', max_length=255, verbose_name='product_images'),
        ),
    ]
