# Generated by Django 5.1.2 on 2025-01-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='request_number',
            field=models.CharField(default=0, editable=False, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
